 void hfont(char *);
 int hnumchars();
 void hsetpath(char *);
 void hgetcharsize(char, float*, float*);
 void hdrawchar(int);
 void htextsize(float, float);
 float hgetfontwidth();
 float hgetfontheight();
 void hgetfontsize(float *, float *);
 float hgetdecender();
 float hgetascender();
 void hcharstr(char *);
 float hstrlength(char *);
 void hboxtext(float, float, float, float, char*);
 void hboxfit(float, float, int);
 void hcentertext(int);
 void hrightjustify(int);
 void hleftjustify(int);
 void hfixedwidth(int);
 void htextang(float);

